_wandb:
    value:
        cli_version: 0.18.2
        m: []
        python_version: 3.11.9
        t:
            "1":
                - 55
            "2":
                - 55
            "3":
                - 13
                - 19
                - 23
                - 55
            "4": 3.11.9
            "5": 0.18.2
            "8":
                - 3
                - 5
            "12": 0.18.2
            "13": windows-amd64
epsilon:
    value: 0.1
